# Generated by Django 6.0.5 on 2026-06-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Raw verification payload from the gateway.'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('chapa', 'Chapa (Ethiopia)'), ('crypto', 'Crypto'), ('cod', 'Cash on delivery')], default='cod', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.URLField(blank=True, help_text='Gateway checkout URL while pending.', max_length=600),
        ),
        migrations.AddField(
            model_name='order',
            name='tx_ref',
            field=models.CharField(blank=True, help_text='Unique reference shared with the payment gateway.', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending payment'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=12),
        ),
    ]
